name: Build IPA
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter (Version compatible)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'

      - name: Fix Package Name and Create iOS
        run: |
          # Forzamos el nombre a minÃºsculas en el pubspec para evitar el error de la imagen
          sed -i '' 's/name: TeVe/name: teve/g' pubspec.yaml
          # Creamos la carpeta de iOS con el nombre correcto
          flutter create . --platforms=ios --project-name=teve
          flutter pub get

      - name: Patch Podfile Deployment Target
        run: |
          # Ajustamos para que Xcode 16 no de error de compatibilidad
          if [ -f ios/Podfile ]; then
            sed -i '' "s/platform :ios, '11.0'/platform :ios, '13.0'/g" ios/Podfile
            echo "post_install do |installer|
              installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                end
              end
            end" >> ios/Podfile
          fi

      - name: Install Dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA (Unsigned)
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: teve-ipa
          path: build/ios/ipa/*.ipa